config/routes.rb
PropsFinder::Application.routes.draw do

  match 'notification_restrictions/user/:id' => 'notification_restrictions#get_by_user'

  resources :notification_restrictions

  match 'images/get_by_property' => 'images#get_by_property'
 
  resources :images

  match 'interests/reset_interests' => 'interests#reset_interests'
  
  resources :interests do
	collection do
		post 'remove_interest'
	end
  end
  
  match 'properties/get_interested' => 'properties#get_interested'

  resources :properties

  match 'users/sign_in' => 'users#sign_in'
  
  match 'users/update_registration_id' => 'users#update_registration_id'
  resources :users
  
  

end

app/models/property.rb
class Property < ActiveRecord::Base
end

app/controllers/properties_controller.rb
require "net/http"
require "net/https"
require "speedy_c2dm"
require "c2dm"
class PropertiesController < ApplicationController

  # GET /get_interested
  # GET /get_interested.json
  def get_interested
  
    @properties = Interest.joins(:property).where("user_id = ?",params[:user_id]).select("properties.*");
    render json: @properties 
	
  end
  
  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @properties }
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @property = Property.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/new
  # GET /properties/new.json
  def new
    @property = Property.new

	
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/1/edit
  def edit
    @property = Property.find(params[:id])
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(params[:property])

    respond_to do |format|
      if @property.save
	  
	  #notify users
	  
		@users = User.all
	  
	  @users.each do |u|

	  #c2dm = C2DM.new("org.feup.cmov.app@gmail.com", "feupcmov01", "PropsFinder")
	  #notification = { :registration_id => u.registration_id, :data => { :message => "Ola" }, :collapse_key => "biteme" }
	  #c2dm.send_notification(notification)

		options = {
		  :registration_id => u.registration_id,
		  :message => @property.id,
		  :extra_data => nil,
		  :collapse_key => "some-collapse-key"
		}
		
		@restrictionPassed = true
		#check if it matches the users price restrictions
		@restriction = NotificationRestriction.where("user_id = ?",u.id)
		
		if not @restriction.empty?
		@restriction = @restriction.first
			if @property.price >= @restriction.minimumPrice && @property.price <= @restriction.maximumPrice 
				@restrictionPassed = true
			else
				@restrictionPassed = false
			end
		end
		
		if @restrictionPassed == true
			@interest = Interest.new(:user_id => u.id, :property_id => @property.id)
			@interest.save
			
			puts @property.id
			#puts u.username
			
			response = SpeedyC2DM::API.send_notification(options)
		end
		puts response
	  end
	  
	  
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render json: @property, status: :created, location: @property }
      else
        format.html { render action: "new" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /properties/1
  # PUT /properties/1.json
  def update
    @property = Property.find(params[:id])

    respond_to do |format|
      if @property.update_attributes(params[:property])
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url }
      format.json { head :ok }
    end
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :property_type %><br />
    <%= f.text_field :property_type %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<h1>Listing properties</h1>

<table>
  <tr>
    <th>Price</th>
    <th>Address</th>
    <th>Type</th>
    <th>City</th>
    <th>Country</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @properties.each do |property| %>
  <tr>
    <td><%= property.price %></td>
    <td><%= property.address %></td>
    <td><%= property.property_type %></td>
    <td><%= property.city %></td>
    <td><%= property.country %></td>
    <td><%= property.description %></td>
    <td><%= link_to 'Show', property %></td>
    <td><%= link_to 'Edit', edit_property_path(property) %></td>
    <td><%= link_to 'Destroy', property, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New property</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Price:</b>
  <%= @property.price %>
</p>

<p>
  <b>Address:</b>
  <%= @property.address %>
</p>

<p>
  <b>Type:</b>
  <%= @property.property_type %>
</p>

<p>
  <b>City:</b>
  <%= @property.city %>
</p>

<p>
  <b>Country:</b>
  <%= @property.country %>
</p>

<p>
  <b>Description:</b>
  <%= @property.description %>
</p>


<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>