config/routes.rb
PropsFinder::Application.routes.draw do

  match 'notification_restrictions/user/:id' => 'notification_restrictions#get_by_user'

  resources :notification_restrictions

  match 'images/get_by_property' => 'images#get_by_property'
 
  resources :images

  match 'interests/reset_interests' => 'interests#reset_interests'
  
  resources :interests do
	collection do
		post 'remove_interest'
	end
  end
  
  match 'properties/get_interested' => 'properties#get_interested'

  resources :properties

  match 'users/sign_in' => 'users#sign_in'
  
  match 'users/update_registration_id' => 'users#update_registration_id'
  resources :users
  
  

end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :user
  belongs_to :property
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController

 def reset_interests
 
	@user = User.find(params[:user_id])
	@properties = Property.all
	  
	  @properties.each do |u|
	  
		@interest = Interest.where("user_id = ? and property_id = ?",params[:user_id],u.id)
		if @interest.empty?
		
			@interest = Interest.new(:user_id=>@user.id, :property_id=>u.id)
			@interest.save
		end
		
	  end
	  
    respond_to do |format|
      format.html { redirect_to interests_url }
      format.json { head :ok }
    end
  end

 # DELETE /interests?user_id=x&property_id=y
  # DELETE /interests/1.json
  def remove_interest
    @interest = Interest.where("user_id = ? and property_id= ?",params[:user_id],params[:property_id])
    @interest.first.destroy

    respond_to do |format|
      format.html { redirect_to interests_url }
      format.json { head :ok }
    end
  end
  
  # GET /interests
  # GET /interests.json
  def index
    @interests = Interest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @interests }
    end
  end

  # GET /interests/1
  # GET /interests/1.json
  def show
    @interest = Interest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @interest }
    end
  end

  # GET /interests/new
  # GET /interests/new.json
  def new
    @interest = Interest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @interest }
    end
  end

  # GET /interests/1/edit
  def edit
    @interest = Interest.find(params[:id])
  end

  # POST /interests
  # POST /interests.json
  def create
    @interest = Interest.new(params[:interest])

    respond_to do |format|
      if @interest.save
        format.html { redirect_to @interest, notice: 'Interest was successfully created.' }
        format.json { render json: @interest, status: :created, location: @interest }
      else
        format.html { render action: "new" }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /interests/1
  # PUT /interests/1.json
  def update
    @interest = Interest.find(params[:id])

    respond_to do |format|
      if @interest.update_attributes(params[:interest])
        format.html { redirect_to @interest, notice: 'Interest was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interests/1
  # DELETE /interests/1.json
  def destroy
    @interest = Interest.find(params[:id])
    @interest.destroy

    respond_to do |format|
      format.html { redirect_to interests_url }
      format.json { head :ok }
    end
  end
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/views/interests/_form.html.erb
<%= form_for(@interest) do |f| %>
  <% if @interest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interest.errors.count, "error") %> prohibited this interest from being saved:</h2>

      <ul>
      <% @interest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :property %><br />
    <%= f.text_field :property %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interests/edit.html.erb
<h1>Editing interest</h1>

<%= render 'form' %>

<%= link_to 'Show', @interest %> |
<%= link_to 'Back', interests_path %>

app/views/interests/index.html.erb
<h1>Listing interests</h1>

<table>
  <tr>
    <th>User</th>
    <th>Property</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @interests.each do |interest| %>
  <tr>
    <td><%= interest.user %></td>
    <td><%= interest.property %></td>
    <td><%= link_to 'Show', interest %></td>
    <td><%= link_to 'Edit', edit_interest_path(interest) %></td>
    <td><%= link_to 'Destroy', interest, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Interest', new_interest_path %>

app/views/interests/new.html.erb
<h1>New interest</h1>

<%= render 'form' %>

<%= link_to 'Back', interests_path %>

app/views/interests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @interest.user %>
</p>

<p>
  <b>Property:</b>
  <%= @interest.property %>
</p>


<%= link_to 'Edit', edit_interest_path(@interest) %> |
<%= link_to 'Back', interests_path %>